(in-package #:autolith)

;;;; -- Test Entry --

(-> run-tests () boolean)
(defun run-tests ()
  "Run Autolith's dependency-free unit tests and return true on success."
  (setf *test-count* 0)
  (let ((configuration (configuration-create
                        :source-root (asdf:system-source-directory :autolith)
                        :working-directory (asdf:system-source-directory :autolith))))
    (test-assert (string= (configuration-model configuration) "gpt-5.6-sol")
                 "the default model is gpt-5.6-sol")
    (let ((*default-model* "gpt-5.6-luna"))
      (test-assert
       (string= (configuration-model
                 (configuration-create
                  :source-root (asdf:system-source-directory :autolith)
                  :working-directory
                  (asdf:system-source-directory :autolith)))
                "gpt-5.6-luna")
       "live default parameters affect newly created configurations"))
    (test-assert (string= (configuration-model
                           (configuration-with-model configuration
                                                     "gpt-5.6-luna"))
                          "gpt-5.6-luna")
                 "model copies swap only the model")
    (test-assert (= (configuration-context-window configuration) 272000)
                 "5.6 models carry the live catalog context window")
    (test-assert (= (configuration-context-window
                     (configuration-with-model configuration "gpt-5.6-terra"))
                    272000)
                 "model copies recompute the context window")
    (test-assert (= (configuration-compaction-token-limit configuration)
                    217600)
                 "compaction triggers at the threshold share of the window")
    (test-assert (handler-case
                     (progn
                       (configuration-with-model configuration "gpt-4")
                       nil)
                   (configuration-error ()
                     t))
                 "model copies reject identifiers outside the 5.6 family")
    (let ((moved (configuration-with-working-directory configuration "tests")))
      (test-assert
       (equal (configuration-working-directory moved)
              (truename (merge-pathnames "tests/"
                                         (configuration-working-directory
                                          configuration))))
       "working-directory copies resolve relative existing directories")
      (test-assert
       (equal (configuration-source-root moved)
              (configuration-source-root configuration))
       "working-directory copies preserve unrelated configuration"))
    (test-assert
     (handler-case
         (progn
           (configuration-with-working-directory configuration "README.org")
           nil)
       (working-directory-error (condition)
         (eq (working-directory-error-stage condition) ':validation)))
     "working-directory copies reject files with a structured condition")
    (test-assert (string= (configuration-reasoning-effort configuration) "ultra")
                 "the default reasoning effort is ultra")
    (test-assert (not (configuration-immutable-p configuration))
                 "ordinary configuration enables active-image mutation tools")
    (test-assert
     (configuration-immutable-p
      (configuration-with-model
       (configuration--clone configuration :immutable-p t)
       "gpt-5.6-luna"))
     "configuration clones preserve immutable mode")
    (test-assert (string= (configuration-wire-effort configuration) "max")
                 "ultra maps to the provider max effort")
    (test-assert
     (string= (configuration-wire-effort
               (configuration-with-reasoning-effort configuration "none"))
              "none")
     "none is passed through as a provider reasoning effort")
    (test-assert (= (json-get (json-object "answer" 42) "answer") 42)
                 "JSON object access preserves values")
    (test-assert (vectorp (json-decode "[1,2,3]"))
                 "JSON arrays have one consistent vector representation")
    (test-bounded-character-reads)
    (let* ((value (json-object "text" "příliš žluťoučký"))
           (encoded (json-encode value))
           (octets (json-encode-utf8 value)))
      (test-assert
       (equalp octets
               (sb-ext:string-to-octets encoded :external-format ':utf-8))
       "direct UTF-8 JSON encoding preserves the compact wire representation")
      (test-assert
       (subtypep (array-element-type octets) '(unsigned-byte 8))
       "direct UTF-8 JSON encoding returns octets without a wide string body"))
    (test-memory-persistence)
    (test-papercuts)
    (test-update-state-and-installation-provenance)
    (test-user-init)
    (test-directory-user-init)
    (test-memory-tools)
    (test-agenda-persistence-and-transport)
    (test-agenda-unbounded-item-count)
    (test-agenda-command)
    (test-agenda-version-one-migration)
    (test-agenda-malformed-state)
    (test-agenda-tools)
    (test-preferences)
    (test-command-permission-persistence)
    (test-command-permission-corruption)
    (test-later-persistence)
    (test-later-malformed-state)
    (test-later-reset-selection)
    (test-request-local-context)
    (test-interpreter-discipline)
    (test-self-review-reminder)
    (test-skills)
    (test-skill-load-tool)
    (test-mcp-configuration)
    (test-directory-configuration)
    (test-mcp-tools)
    (test-mcp-reload-registry-rollback)
    (test-mcp-reload-registry-isolation)
    (test-mcp-reload-transaction-boundary)
    (run-application-command-tests)
    (test-project-adaptations)
    (test-conversation-identifiers)
    (test-conversation-persistence)
    (test-conversation-private-storage)
    (test-conversation-origin-directory)
    (test-conversation-model-selection)
    (test-conversation-cross-family-reasoning)
    (test-conversation-compaction)
    (test-conversation-native-compaction)
    (test-conversation-working-seconds)
    (test-conversation-picker-metadata-stability)
    (test-conversation-picker-search)
    (test-conversation-deletion)
    (test-workspace-plan)
    (test-authentication-store)
    (test-authentication-bootstrap-and-refresh)
    (test-grok-authentication)
    (test-provider-request)
    (test-provider-native-compaction)
    (test-provider-rate-limits)
    (test-provider-stream-decoding)
    (test-provider-stream-failures)
    (test-provider-stream-error-classification)
    (test-provider-transport-boundary)
    (test-provider-credential-echo-containment)
    (test-provider-authentication-retries)
    (test-provider-stream-retries)
    (test-grok-provider)
    (test-openai-compatible-provider-bootstrap)
    (test-openai-compatible-provider-deferred-main-validation)
    (test-openai-compatible-provider-bare-auth-selection)
    (test-openai-compatible-provider-discovery-is-on-demand)
    (test-openai-compatible-provider-model-cache-boundary)
    (test-openai-compatible-provider-authentication-bootstrap)
    (test-openai-compatible-provider-discovery)
    (test-openai-compatible-provider-registration-identity)
     (test-provider-sse-bounds)
    (test-openai-compatible-provider)
    (test-fireworks-provider)
    (test-resource-protocol)
    (test-resource-edit-operation-schema)
    (test-workspace-file-resources)
    (test-agenda-resources)
    (test-memory-resources)
    (test-memory-resource-mutations)
    (test-tool-registry)
    (test-workspace-tools)
    (test-search-tools)
    (test-lisp-image-manifests)
    (test-lisp-worker-protocol)
    (test-lisp-scratchpad-tools)
     (test-lisp-worker-image-snapshot)
    (test-self-tools)
    (test-self-definition-installation-rollback)
    (test-self-application-command-definitions)
    (test-self-restart-selection)
    (test-self-discard)
    (test-durable-self-mutation)
    (test-durable-definition-publication-boundary)
    (test-generation-manifest)
    (test-active-image-build-record)
    (test-image-commit-replay-probe)
    (test-crash-capsule-correlation)
    (run-recovery-tests)
    (run-device-authentication-tests)
    (run-grok-device-authentication-tests)
    (run-agent-tests)
    (test-task-agent-native-reader)
    (test-task-agent-discovery-precedence)
    (test-task-agents-tool)
    (test-task-tool-default-argument-types)
    (test-task-native-output-contracts)
    (test-task-yield-contract)
    (test-task-abort-control-condition)
    (test-task-orchestration)
    (test-task-child-shared-agent-loop)
    (test-task-running-cancellation)
    (test-task-runtime-deadline)
    (test-task-nested-parent-cancellation)
    (test-task-admission-cancellation-barrier)
    (test-task-hurry-up-admission-races)
    (test-task-publication-coherence)
    (test-task-terminal-wakeup-ordering)
    (test-task-job-visibility)
    (test-task-job-list-pagination)
    (test-task-refresh-after-delayed-close)
    (test-task-terminal-cancellation-and-publication)
    (test-task-retention-and-admission)
    (test-task-evicted-identity-retention)
    (test-task-live-activity-snapshots)
    (test-task-run-native-manifest)
    (test-task-scheduler)
    (run-terminal-tests)
    (test-localgroup-terminal-restart)
    (test-localgroup-protocol)
    (test-localgroup-attachments)
    (test-localgroup-handoff-records)
    (test-localgroup-handoff-scheduling)
    (test-localgroup-process-handoff)
    (test-localgroup-handoff-cancellation)
    (test-localgroup-fresh-startup-selection)
    (run-layout-tests)
    (run-markdown-tests)
    (test-release-scripts)
    (test-release-server)
    (task-tests--close-orchestrators)
    (run-application-tests))
  (format t "~&~:D Autolith tests passed.~%" *test-count*)
  t)
